use_frameworks!

platform :ios, '9.0'

target 'CarHireLocationsPOD_Example' do
  pod 'CarHireLocationsPOD', :path => '../'

  target 'CarHireLocationsPOD_Tests' do
    inherit! :search_paths

    
  end
end
